### ISSUE TITLE
Added version information to vgl

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/vgl#31]

**Comment by aashish24** [comment]
@jbeezley I believe this one is done as well.

**Comment by jbeezley** [comment]
I'm not sure what this issue means.  There is a version number in `package.json`, but that isn't exposed anywhere in vgl like we do in geojs as `geo.version`.

**Comment by aashish24** [comment]
okay, in that case this is not done then.

**Comment by manthey** [comment]
Added in PR #94.
