### ISSUE TITLE
Add the ability to dynamically change data properties

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/vgl#66]
Currently, to change any property of data, we have to completely reconstruct the geometry.  It is desirable to have a method to change the internal source buffers so that features can be animated faster.  This requires creating buffers with the gl.DYNAMIC_DRAW flag and a method to update the buffer using gl.bufferSubData.

**Comment by aashish24** [comment]
@manthey do we need to do more for this issue?

**Comment by manthey** [comment]
At the moment the client has to call something convoluted like `feature.actors()[0].mapper().getSourceBuffer(<buffer name>)` and `feature.actors()[0].mapper().updateSourceBuffer(<buffer name>)`.  There should be a cleaner way of doing this.

**Comment by aashish24** [comment]
Since we are talking about VGL here, whats relevant is 

mapper().getSourceBuffer(<buffer name>)

Which to me seems like a reasonable API for VGL. Are you thinking GeoJS here?

**Comment by manthey** [comment]
Probably we could make a few convenience functions in geojs and declare this issue closed in vgl.

**Comment by aashish24** [comment]
> Probably we could make a few convenience functions in geojs and declare this issue closed in vgl.

Sounds reasonable to me.

**Comment by aashish24** [comment]
@manthey FYI: we have a related issue in GeoJS here: https://github.com/OpenGeoscience/geojs/issues/406
